Reversi4colorWpf.MainWindow Class Reference
MainWindow
Public Member Functions
static bool DeleteObject (IntPtr hObject)
gdi32.dllのDeleteObjectメソッドの使用を宣言する。
MainWindow ()
コンストラクタ
ImageSource ToImageSource (Bitmap bmp)
BITMAPかImageSourceに変換
ReversiSetting LoadSettingXml (string path)
設定XMLファイルロード
int SaveSettingXml (string path, ref ReversiSetting appSet)
設定XMLファイルセーブ
void appInit ()
アプリ初期化
void ViewMsgDlg (string title, string msg)
メッセージダイアログ
void ViewMsgDlgLocal (string title, string msg)
メッセージダイアログ
void DrawSingle (int y, int x, int sts, int bk, string text)
1マス描画
void DrawSingleLocal (int y, int x, int sts, int bk, string text)
1マス描画
void CurColMsg (string text)
現在の色メッセージ
void CurColMsgLocal (string text)
現在の色メッセージ
void CurStsMsg (string text)
現在のステータスメッセージ
void CurStsMsgLocal (string text)
現在のステータスメッセージ
void InitializeComponent ()
InitializeComponent
void InitializeComponent ()
InitializeComponent
void InitializeComponent ()
InitializeComponent
void InitializeComponent ()
InitializeComponent
Public Attributes
ReversiSetting m_AppSettings
アプリ設定
ReversiPlay m_ReversiPlay
リバーシ本体
Private Member Functions
delegate void ViewMsgDlgDelegate (string title, string msg)
delegate void DrawSingleDelegate (int y, int x, int sts, int bk, string text)
delegate void CurColMsgDelegate (string text)
delegate void CurStsMsgDelegate (string text)
delegate void Reversi_ResizeEndDelegate (object sender, EventArgs e)
void pictureBox_Click (object sender, MouseButtonEventArgs e)
マスクリック
void btn_reset_Click (object sender, RoutedEventArgs e)
リセットクリック
void btn_setting_Click (object sender, RoutedEventArgs e)
void Reversi_ResizeEnd (object sender, EventArgs e)
void Window_SizeChanged (object sender, SizeChangedEventArgs e)
ウィンドウサイズ変更
void OnTimedEvent (object source, ElapsedEventArgs e)
タイマーイベント
void System.Windows.Markup.IComponentConnector. Connect (int connectionId, object target)
void System.Windows.Markup.IComponentConnector. Connect (int connectionId, object target)
void System.Windows.Markup.IComponentConnector. Connect (int connectionId, object target)
void System.Windows.Markup.IComponentConnector. Connect (int connectionId, object target)
Private Attributes
System.Windows.Size oldSize
リサイズ前のサイズ
bool _contentLoaded
Static Private Attributes
static System.Timers.Timer aTimer
タイマー
Detailed Description
MainWindow
MainWindow.xaml の相互作用ロジッククラス
Definition at line 47 of file MainWindow.xaml.cs.
Constructor & Destructor Documentation
MainWindow()
Reversi4colorWpf.MainWindow.MainWindow ()
コンストラクタ
Returns
ありません
Author
Yuta Yoshinaga
Date
2017.10.20
Definition at line 71 of file MainWindow.xaml.cs.
Member Function Documentation
appInit()
void Reversi4colorWpf.MainWindow.appInit ()
アプリ初期化
Returns
ありません
Author
Yuta Yoshinaga
Date
2017.10.20
Definition at line 198 of file MainWindow.xaml.cs.
Referenced by Reversi4colorWpf.MainWindow.btn_reset_Click(), and Reversi4colorWpf.MainWindow.MainWindow().
btn_reset_Click()
void Reversi4colorWpf.MainWindow.btn_reset_Click (object sender, RoutedEventArgs e) [private]
リセットクリック
Parameters
in object sender
in RoutedEventArgs e
Returns
ありません
Author
Yuta Yoshinaga
Date
2017.10.20
Definition at line 526 of file MainWindow.xaml.cs.
Referenced by Reversi4colorWpf.MainWindow.InitializeComponent().
CurColMsg()
void Reversi4colorWpf.MainWindow.CurColMsg (string text)
現在の色メッセージ
Parameters
in string text テキスト
Returns
ありません
Author
Yuta Yoshinaga
Date
2017.10.20
Definition at line 446 of file MainWindow.xaml.cs.
Referenced by Reversi4colorWpf.MainWindow.MainWindow().
CurColMsgLocal()
void Reversi4colorWpf.MainWindow.CurColMsgLocal (string text)
現在の色メッセージ
Parameters
in string text テキスト
Returns
ありません
Author
Yuta Yoshinaga
Date
2017.10.20
Definition at line 460 of file MainWindow.xaml.cs.
Referenced by Reversi4colorWpf.MainWindow.CurColMsg().
CurStsMsg()
void Reversi4colorWpf.MainWindow.CurStsMsg (string text)
現在のステータスメッセージ
Parameters
in string text テキスト
Returns
ありません
Author
Yuta Yoshinaga
Date
2017.10.20
Definition at line 474 of file MainWindow.xaml.cs.
Referenced by Reversi4colorWpf.MainWindow.MainWindow().
CurStsMsgLocal()
void Reversi4colorWpf.MainWindow.CurStsMsgLocal (string text)
現在のステータスメッセージ
Parameters
in string text テキスト
Returns
ありません
Author
Yuta Yoshinaga
Date
2017.10.20
Definition at line 488 of file MainWindow.xaml.cs.
Referenced by Reversi4colorWpf.MainWindow.CurStsMsg().
DrawSingle()
void Reversi4colorWpf.MainWindow.DrawSingle (int y, int x, int sts, int bk, string text)
1マス描画
Parameters
in int y Y座標
in int x X座標
in int sts ステータス
in int bk 背景
in string text テキスト
Returns
ありません
Author
Yuta Yoshinaga
Date
2017.10.20
Definition at line 299 of file MainWindow.xaml.cs.
Referenced by Reversi4colorWpf.MainWindow.MainWindow().
DrawSingleLocal()
void Reversi4colorWpf.MainWindow.DrawSingleLocal (int y, int x, int sts, int bk, string text)
1マス描画
Parameters
in int y Y座標
in int x X座標
in int sts ステータス
in int bk 背景
in string text テキスト
Returns
ありません
Author
Yuta Yoshinaga
Date
2017.10.20
Definition at line 317 of file MainWindow.xaml.cs.
Referenced by Reversi4colorWpf.MainWindow.DrawSingle().
InitializeComponent() [1/4]
void Reversi4colorWpf.MainWindow.InitializeComponent ()
InitializeComponent
Definition at line 3290 of file MainWindow.g.i.cs.
InitializeComponent() [2/4]
void Reversi4colorWpf.MainWindow.InitializeComponent ()
InitializeComponent
Definition at line 3290 of file MainWindow.g.cs.
InitializeComponent() [3/4]
void Reversi4colorWpf.MainWindow.InitializeComponent ()
InitializeComponent
Definition at line 3290 of file MainWindow.g.cs.
Referenced by Reversi4colorWpf.MainWindow.MainWindow().
InitializeComponent() [4/4]
void Reversi4colorWpf.MainWindow.InitializeComponent ()
InitializeComponent
Definition at line 3290 of file MainWindow.g.i.cs.
LoadSettingXml()
ReversiSetting Reversi4colorWpf.MainWindow.LoadSettingXml (string path)
設定XMLファイルロード
Parameters
in string path 設定XMLファイルパス
Returns
ReversiSettingオブジェクトインスタンス
Author
Yuta Yoshinaga
Date
2017.10.20
Definition at line 132 of file MainWindow.xaml.cs.
Referenced by Reversi4colorWpf.MainWindow.MainWindow().
OnTimedEvent()
void Reversi4colorWpf.MainWindow.OnTimedEvent (object source, ElapsedEventArgs e) [private]
タイマーイベント
Parameters
in object source
in ElapsedEventArgs e
Returns
ありません
Author
Yuta Yoshinaga
Date
2017.10.20
Definition at line 629 of file MainWindow.xaml.cs.
Referenced by Reversi4colorWpf.MainWindow.Window_SizeChanged().
pictureBox_Click()
void Reversi4colorWpf.MainWindow.pictureBox_Click (object sender, MouseButtonEventArgs e) [private]
マスクリック
Parameters
in object sender
in MouseButtonEventArgs e
Returns
ありません
Author
Yuta Yoshinaga
Date
2017.10.20
Definition at line 503 of file MainWindow.xaml.cs.
Referenced by Reversi4colorWpf.MainWindow.InitializeComponent().
SaveSettingXml()
int Reversi4colorWpf.MainWindow.SaveSettingXml (string path, ref ReversiSetting appSet)
設定XMLファイルセーブ
Parameters
in string path 設定XMLファイルパス
out ReversiSetting appSet 設定XMLファイルオブジェクト
Returns
0 : 成功 それ以外 : 失敗
Author
Yuta Yoshinaga
Date
2017.10.20
Definition at line 166 of file MainWindow.xaml.cs.
Referenced by Reversi4colorWpf.MainWindow.btn_reset_Click(), and Reversi4colorWpf.MainWindow.MainWindow().
ToImageSource()
ImageSource Reversi4colorWpf.MainWindow.ToImageSource (Bitmap bmp)
BITMAPかImageSourceに変換
Parameters
in Bitmap bmp
Returns
ImageSource
Author
Yuta Yoshinaga
Date
2017.10.20
Definition at line 113 of file MainWindow.xaml.cs.
Referenced by Reversi4colorWpf.MainWindow.DrawSingleLocal().
ViewMsgDlg()
void Reversi4colorWpf.MainWindow.ViewMsgDlg (string title, string msg)
メッセージダイアログ
Parameters
in string title タイトル
in string msg メッセージ
Returns
ありません
Author
Yuta Yoshinaga
Date
2017.10.20
Definition at line 266 of file MainWindow.xaml.cs.
Referenced by Reversi4colorWpf.MainWindow.MainWindow().
ViewMsgDlgLocal()
void Reversi4colorWpf.MainWindow.ViewMsgDlgLocal (string title, string msg)
メッセージダイアログ
Parameters
in string title タイトル
in string msg メッセージ
Returns
ありません
Author
Yuta Yoshinaga
Date
2017.10.20
Definition at line 281 of file MainWindow.xaml.cs.
Referenced by Reversi4colorWpf.MainWindow.ViewMsgDlg().
Window_SizeChanged()
void Reversi4colorWpf.MainWindow.Window_SizeChanged (object sender, SizeChangedEventArgs e) [private]
ウィンドウサイズ変更
Parameters
in object sender
in SizeChangedEventArgs e
Returns
ありません
Author
Yuta Yoshinaga
Date
2017.10.20
Definition at line 600 of file MainWindow.xaml.cs.
The documentation for this class was generated from the following files:
MainWindow.xaml.cs
obj/Debug/MainWindow.g.cs
obj/Debug/MainWindow.g.i.cs