Reversi4colorWpf.MyReversi Class Reference
リバーシクラス
Public Member Functions
MyReversi (int masuCnt, int masuMax)
コンストラクタ
MyReversi Clone ()
コピー
void reset ()
リセット
void AnalysisReversi (int bPassEna, int wPassEna, int lPassEna, int rPassEna)
解析を行う
int getMasuSts (int y, int x)
マスステータスを取得
int getMasuStsOld (int y, int x)
以前のマスステータスを取得
int getMasuStsEna (int color, int y, int x)
指定座標に指定色を置けるかチェック
int getMasuStsCnt (int color, int y, int x)
指定座標の獲得コマ数取得
int getColorEna (int color)
指定色が現在置ける場所があるかチェック
int getGameEndSts ()
ゲーム終了かチェック
int setMasuSts (int color, int y, int x)
指定座標にコマを置く
int setMasuStsForcibly (int color, int y, int x)
指定座標にコマを強制的に置く
int setMasuCnt (int cnt)
マスの数変更
ReversiPoint getPoint (int color, int num)
ポイント座標取得
int getPointCnt (int color)
ポイント座標数取得
int getBetCnt (int color)
コマ数取得
int getPassEna (int color, int y, int x)
パス判定
ReversiHistory getHistory (int num)
履歴取得
int getHistoryCnt ()
履歴数取得
ReversiAnz getPointAnz (int color, int y, int x)
ポイント座標解析取得
int checkEdge (int color, int y, int x)
角の隣に置いても角を取られないマス検索
int getEdgeSideZero (int y, int x)
指定座標が角か取得
int getEdgeSideOne (int y, int x)
指定座標が角の一つ手前か取得
int getEdgeSideTwo (int y, int x)
指定座標が角の二つ手前か取得
int getEdgeSideThree (int y, int x)
指定座標が角の三つ以上手前か取得
Properties
int[,] mMasuSts [get, set]
int[,] mMasuStsOld [get, set]
int[,] mMasuStsEnaB [get, set]
int[,] mMasuStsCntB [get, set]
int[,] mMasuStsPassB [get, set]
ReversiAnz[,] mMasuStsAnzB [get, set]
ReversiPoint[] mMasuPointB [get, set]
int mMasuPointCntB [get, set]
int mMasuBetCntB [get, set]
int[,] mMasuStsEnaW [get, set]
int[,] mMasuStsCntW [get, set]
int[,] mMasuStsPassW [get, set]
ReversiAnz[,] mMasuStsAnzW [get, set]
ReversiPoint[] mMasuPointW [get, set]
int mMasuPointCntW [get, set]
int mMasuBetCntW [get, set]
int[,] mMasuStsEnaL [get, set]
int[,] mMasuStsCntL [get, set]
int[,] mMasuStsPassL [get, set]
ReversiAnz[,] mMasuStsAnzL [get, set]
ReversiPoint[] mMasuPointL [get, set]
int mMasuPointCntL [get, set]
int mMasuBetCntL [get, set]
int[,] mMasuStsEnaR [get, set]
int[,] mMasuStsCntR [get, set]
int[,] mMasuStsPassR [get, set]
ReversiAnz[,] mMasuStsAnzR [get, set]
ReversiPoint[] mMasuPointR [get, set]
int mMasuPointCntR [get, set]
int mMasuBetCntR [get, set]
int mMasuCnt [get, set]
int mMasuCntMax [get, set]
int mMasuHistCur [get, set]
ReversiHistory[] mMasuHist [get, set]
Private Member Functions
int makeMasuSts (int color)
各コマの置ける場所等のステータス作成
void revMasuSts (int color, int y, int x)
コマをひっくり返す
int checkPara (int para, int min, int max)
パラメーター範囲チェック
void AnalysisReversiBlack ()
解析を行う(黒)
void AnalysisReversiWhite ()
解析を行う(白)
void AnalysisReversiBlue ()
解析を行う(青)
void AnalysisReversiRed ()
解析を行う(赤)
Private Attributes
int[,] _mMasuSts
マスの状態
int[,] _mMasuStsOld
以前のマスの状態
int[,] _mMasuStsEnaB
黒の置ける場所
int[,] _mMasuStsCntB
黒の獲得コマ数
int[,] _mMasuStsPassB
黒が相手をパスさせる場所
ReversiAnz[,] _mMasuStsAnzB
黒がその場所に置いた場合の解析結果
ReversiPoint[] _mMasuPointB
黒の置ける場所座標一覧
int _mMasuPointCntB
黒の置ける場所座標一覧数
int _mMasuBetCntB
黒コマ数
int[,] _mMasuStsEnaW
白の置ける場所
int[,] _mMasuStsCntW
白の獲得コマ数
int[,] _mMasuStsPassW
白が相手をパスさせる場所
ReversiAnz[,] _mMasuStsAnzW
白がその場所に置いた場合の解析結果
ReversiPoint[] _mMasuPointW
白の置ける場所座標一覧
int _mMasuPointCntW
白の置ける場所座標一覧数
int _mMasuBetCntW
白コマ数
int[,] _mMasuStsEnaL
青の置ける場所
int[,] _mMasuStsCntL
青の獲得コマ数
int[,] _mMasuStsPassL
青が相手をパスさせる場所
ReversiAnz[,] _mMasuStsAnzL
青がその場所に置いた場合の解析結果
ReversiPoint[] _mMasuPointL
青の置ける場所座標一覧
int _mMasuPointCntL
青の置ける場所座標一覧数
int _mMasuBetCntL
青コマ数
int[,] _mMasuStsEnaR
赤の置ける場所
int[,] _mMasuStsCntR
赤の獲得コマ数
int[,] _mMasuStsPassR
赤が相手をパスさせる場所
ReversiAnz[,] _mMasuStsAnzR
赤がその場所に置いた場合の解析結果
ReversiPoint[] _mMasuPointR
赤の置ける場所座標一覧
int _mMasuPointCntR
赤の置ける場所座標一覧数
int _mMasuBetCntR
赤コマ数
int _mMasuCnt
縦横マス数
int _mMasuCntMax
縦横マス最大数
int _mMasuHistCur
履歴現在位置
ReversiHistory[] _mMasuHist
履歴
Detailed Description
リバーシクラス
Definition at line 30 of file MyReversi.cs.
Constructor & Destructor Documentation
Reversi4colorWpf.MyReversi.MyReversi (int masuCnt, int masuMax)
コンストラクタ
Parameters
in int masuCnt 縦横マス数
in int masuMax 縦横マス最大数
Returns
ありません
Author
Yuta Yoshinaga
Date
2017.10.20
Definition at line 252 of file MyReversi.cs.
Member Function Documentation
void Reversi4colorWpf.MyReversi.AnalysisReversi (int bPassEna, int wPassEna, int lPassEna, int rPassEna)
解析を行う
Parameters
in int bPassEna 1=黒パス有効
in int wPassEna 1=白パス有効
in int lPassEna 1=青パス有効
in int rPassEna 1=赤パス有効
Returns
ありません
Author
Yuta Yoshinaga
Date
2017.10.20
Definition at line 1628 of file MyReversi.cs.
Referenced by Reversi4colorWpf.ReversiPlay.reset(), Reversi4colorWpf.ReversiPlay.reversiPlay(), and Reversi4colorWpf.ReversiPlay.reversiPlayCpu().
void Reversi4colorWpf.MyReversi.AnalysisReversiBlack () [private]
解析を行う(黒)
Returns
ありません
Author
Yuta Yoshinaga
Date
2017.10.20
Definition at line 848 of file MyReversi.cs.
Referenced by Reversi4colorWpf.MyReversi.AnalysisReversi().
void Reversi4colorWpf.MyReversi.AnalysisReversiBlue () [private]
解析を行う(青)
Returns
ありません
Author
Yuta Yoshinaga
Date
2017.10.20
Definition at line 1234 of file MyReversi.cs.
Referenced by Reversi4colorWpf.MyReversi.AnalysisReversi().
void Reversi4colorWpf.MyReversi.AnalysisReversiRed () [private]
解析を行う(赤)
Returns
ありません
Author
Yuta Yoshinaga
Date
2017.10.20
Definition at line 1429 of file MyReversi.cs.
Referenced by Reversi4colorWpf.MyReversi.AnalysisReversi().
void Reversi4colorWpf.MyReversi.AnalysisReversiWhite () [private]
解析を行う(白)
Returns
ありません
Author
Yuta Yoshinaga
Date
2017.10.20
Definition at line 1041 of file MyReversi.cs.
Referenced by Reversi4colorWpf.MyReversi.AnalysisReversi().
int Reversi4colorWpf.MyReversi.checkEdge (int color, int y, int x)
角の隣に置いても角を取られないマス検索
Parameters
in int color コマ色
in int y マスのY座標
in int x マスのX座標
Returns
0 : 取られる それ以外 : 取られない
Author
Yuta Yoshinaga
Date
2017.10.20
Definition at line 2024 of file MyReversi.cs.
Referenced by Reversi4colorWpf.MyReversi.AnalysisReversiBlack(), Reversi4colorWpf.MyReversi.AnalysisReversiBlue(), Reversi4colorWpf.MyReversi.AnalysisReversiRed(), Reversi4colorWpf.MyReversi.AnalysisReversiWhite(), and Reversi4colorWpf.ReversiPlay.reversiPlayCpu().
int Reversi4colorWpf.MyReversi.checkPara (int para, int min, int max) [private]
パラメーター範囲チェック
Parameters
in int para チェックパラメーター
in int min パラメーター最小値
in int max パラメーター最大値
Returns
0 : 成功 それ以外 : 失敗
Author
Yuta Yoshinaga
Date
2017.10.20
Definition at line 833 of file MyReversi.cs.
Referenced by Reversi4colorWpf.MyReversi.getHistory(), Reversi4colorWpf.MyReversi.getMasuSts(), Reversi4colorWpf.MyReversi.getMasuStsCnt(), Reversi4colorWpf.MyReversi.getMasuStsEna(), Reversi4colorWpf.MyReversi.getMasuStsOld(), Reversi4colorWpf.MyReversi.getPassEna(), Reversi4colorWpf.MyReversi.getPoint(), Reversi4colorWpf.MyReversi.getPointAnz(), and Reversi4colorWpf.MyReversi.setMasuCnt().
MyReversi Reversi4colorWpf.MyReversi.Clone ()
コピー
Returns
オブジェクトコピー
Author
Yuta Yoshinaga
Date
2017.10.20
Definition at line 342 of file MyReversi.cs.
int Reversi4colorWpf.MyReversi.getBetCnt (int color)
コマ数取得
Parameters
in int color コマ色
Returns
コマ数取得
Author
Yuta Yoshinaga
Date
2017.10.20
Definition at line 1921 of file MyReversi.cs.
Referenced by Reversi4colorWpf.ReversiPlay.execMessage(), Reversi4colorWpf.ReversiPlay.gameEndAnimExec(), Reversi4colorWpf.ReversiPlay.reversiPlay(), Reversi4colorWpf.ReversiPlay.reversiPlayCpu(), Reversi4colorWpf.ReversiPlay.reversiPlayEnd(), and Reversi4colorWpf.ReversiPlay.reversiPlaySub().
int Reversi4colorWpf.MyReversi.getColorEna (int color)
指定色が現在置ける場所があるかチェック
Parameters
in int color コマ色
Returns
0 : 成功 それ以外 : 失敗
Author
Yuta Yoshinaga
Date
2017.10.20
Definition at line 1761 of file MyReversi.cs.
Referenced by Reversi4colorWpf.MyReversi.AnalysisReversiBlack(), Reversi4colorWpf.MyReversi.AnalysisReversiBlue(), Reversi4colorWpf.MyReversi.AnalysisReversiRed(), Reversi4colorWpf.MyReversi.AnalysisReversiWhite(), Reversi4colorWpf.MyReversi.getGameEndSts(), Reversi4colorWpf.ReversiPlay.reversiPlay(), and Reversi4colorWpf.ReversiPlay.reversiPlaySub().
int Reversi4colorWpf.MyReversi.getEdgeSideOne (int y, int x)
指定座標が角の一つ手前か取得
Parameters
in int y Y座標
in int x X座標
Returns
0 : 成功 それ以外 : 失敗
Author
Yuta Yoshinaga
Date
2017.10.20
Definition at line 2166 of file MyReversi.cs.
Referenced by Reversi4colorWpf.MyReversi.AnalysisReversiBlack(), Reversi4colorWpf.MyReversi.AnalysisReversiBlue(), Reversi4colorWpf.MyReversi.AnalysisReversiRed(), Reversi4colorWpf.MyReversi.AnalysisReversiWhite(), and Reversi4colorWpf.ReversiPlay.reversiPlayCpu().
int Reversi4colorWpf.MyReversi.getEdgeSideThree (int y, int x)
指定座標が角の三つ以上手前か取得
Parameters
in int y Y座標
in int x X座標
Returns
0 : 成功 それ以外 : 失敗
Author
Yuta Yoshinaga
Date
2017.10.20
Definition at line 2230 of file MyReversi.cs.
Referenced by Reversi4colorWpf.MyReversi.AnalysisReversiBlack(), Reversi4colorWpf.MyReversi.AnalysisReversiBlue(), Reversi4colorWpf.MyReversi.AnalysisReversiRed(), Reversi4colorWpf.MyReversi.AnalysisReversiWhite(), and Reversi4colorWpf.ReversiPlay.reversiPlayCpu().
int Reversi4colorWpf.MyReversi.getEdgeSideTwo (int y, int x)
指定座標が角の二つ手前か取得
Parameters
in int y Y座標
in int x X座標
Returns
0 : 成功 それ以外 : 失敗
Author
Yuta Yoshinaga
Date
2017.10.20
Definition at line 2198 of file MyReversi.cs.
Referenced by Reversi4colorWpf.MyReversi.AnalysisReversiBlack(), Reversi4colorWpf.MyReversi.AnalysisReversiBlue(), Reversi4colorWpf.MyReversi.AnalysisReversiRed(), Reversi4colorWpf.MyReversi.AnalysisReversiWhite(), and Reversi4colorWpf.ReversiPlay.reversiPlayCpu().
int Reversi4colorWpf.MyReversi.getEdgeSideZero (int y, int x)
指定座標が角か取得
Parameters
in int y Y座標
in int x X座標
Returns
0 : 成功 それ以外 : 失敗
Author
Yuta Yoshinaga
Date
2017.10.20
Definition at line 2142 of file MyReversi.cs.
Referenced by Reversi4colorWpf.MyReversi.AnalysisReversiBlack(), Reversi4colorWpf.MyReversi.AnalysisReversiBlue(), Reversi4colorWpf.MyReversi.AnalysisReversiRed(), Reversi4colorWpf.MyReversi.AnalysisReversiWhite(), and Reversi4colorWpf.ReversiPlay.reversiPlayCpu().
int Reversi4colorWpf.MyReversi.getGameEndSts ()
ゲーム終了かチェック
Returns
0 : 続行 それ以外 : ゲーム終了
Author
Yuta Yoshinaga
Date
2017.10.20
Definition at line 1783 of file MyReversi.cs.
Referenced by Reversi4colorWpf.ReversiPlay.reversiPlay(), and Reversi4colorWpf.ReversiPlay.reversiPlaySub().
ReversiHistory Reversi4colorWpf.MyReversi.getHistory (int num)
履歴取得
Parameters
in int num ポイント
Returns
履歴 null : 失敗
Author
Yuta Yoshinaga
Date
2017.10.20
Definition at line 1966 of file MyReversi.cs.
int Reversi4colorWpf.MyReversi.getHistoryCnt ()
履歴数取得
Returns
履歴数
Author
Yuta Yoshinaga
Date
2017.10.20
Definition at line 1983 of file MyReversi.cs.
int Reversi4colorWpf.MyReversi.getMasuSts (int y, int x)
マスステータスを取得
Parameters
in int y 取得するマスのY座標
in int x 取得するマスのX座標
Returns
-1 : 失敗 それ以外 : マスステータス
Author
Yuta Yoshinaga
Date
2017.10.20
Definition at line 1682 of file MyReversi.cs.
Referenced by Reversi4colorWpf.MyReversi.checkEdge(), Reversi4colorWpf.ReversiPlay.drawUpdate(), and Reversi4colorWpf.ReversiPlay.execMessage().
int Reversi4colorWpf.MyReversi.getMasuStsCnt (int color, int y, int x)
指定座標の獲得コマ数取得
Parameters
in int color コマ色
in int y マスのY座標
in int x マスのX座標
Returns
-1 : 失敗 それ以外 : 獲得コマ数
Author
Yuta Yoshinaga
Date
2017.10.20
Definition at line 1740 of file MyReversi.cs.
Referenced by Reversi4colorWpf.ReversiPlay.execMessage(), and Reversi4colorWpf.ReversiPlay.reversiPlayCpu().
int Reversi4colorWpf.MyReversi.getMasuStsEna (int color, int y, int x)
指定座標に指定色を置けるかチェック
Parameters
in int color コマ色
in int y マスのY座標
in int x マスのX座標
Returns
1 : 成功 それ以外 : 失敗
Author
Yuta Yoshinaga
Date
2017.10.20
Definition at line 1717 of file MyReversi.cs.
Referenced by Reversi4colorWpf.MyReversi.AnalysisReversiBlack(), Reversi4colorWpf.MyReversi.AnalysisReversiBlue(), Reversi4colorWpf.MyReversi.AnalysisReversiRed(), Reversi4colorWpf.MyReversi.AnalysisReversiWhite(), Reversi4colorWpf.ReversiPlay.execMessage(), Reversi4colorWpf.MyReversi.getColorEna(), Reversi4colorWpf.ReversiPlay.reversiPlayCpu(), and Reversi4colorWpf.MyReversi.setMasuSts().
int Reversi4colorWpf.MyReversi.getMasuStsOld (int y, int x)
以前のマスステータスを取得
Parameters
in int y 取得するマスのY座標
in int x 取得するマスのX座標
Returns
-1 : 失敗 それ以外 : マスステータス
Author
Yuta Yoshinaga
Date
2017.10.20
Definition at line 1699 of file MyReversi.cs.
Referenced by Reversi4colorWpf.ReversiPlay.drawUpdate().
int Reversi4colorWpf.MyReversi.getPassEna (int color, int y, int x)
パス判定
Parameters
in int color コマ色
in int y マスのY座標
in int x マスのX座標
Returns
パス判定
0 : NOT PASS
1 : PASS
Author
Yuta Yoshinaga
Date
2017.10.20
Definition at line 1945 of file MyReversi.cs.
Referenced by Reversi4colorWpf.ReversiPlay.reversiPlayCpu().
ReversiPoint Reversi4colorWpf.MyReversi.getPoint (int color, int num)
ポイント座標取得
Parameters
in int color コマ色
in int num ポイント
Returns
ポイント座標 null : 失敗
Author
Yuta Yoshinaga
Date
2017.10.20
Definition at line 1881 of file MyReversi.cs.
Referenced by Reversi4colorWpf.ReversiPlay.reset(), and Reversi4colorWpf.ReversiPlay.reversiPlayCpu().
ReversiAnz Reversi4colorWpf.MyReversi.getPointAnz (int color, int y, int x)
ポイント座標解析取得
Parameters
in int color コマ色
in int y マスのY座標
in int x マスのX座標
Returns
ポイント座標解析 null : 失敗
Author
Yuta Yoshinaga
Date
2017.10.20
Definition at line 2001 of file MyReversi.cs.
Referenced by Reversi4colorWpf.ReversiPlay.reversiPlayCpu().
int Reversi4colorWpf.MyReversi.getPointCnt (int color)
ポイント座標数取得
Parameters
in int color コマ色
Returns
ポイント座標数取得
Author
Yuta Yoshinaga
Date
2017.10.20
Definition at line 1902 of file MyReversi.cs.
Referenced by Reversi4colorWpf.MyReversi.AnalysisReversiBlack(), Reversi4colorWpf.MyReversi.AnalysisReversiBlue(), Reversi4colorWpf.MyReversi.AnalysisReversiRed(), Reversi4colorWpf.MyReversi.AnalysisReversiWhite(), Reversi4colorWpf.ReversiPlay.reset(), and Reversi4colorWpf.ReversiPlay.reversiPlayCpu().
int Reversi4colorWpf.MyReversi.makeMasuSts (int color) [private]
各コマの置ける場所等のステータス作成
Parameters
in int color ステータスを作成するコマ
Returns
ありません
Author
Yuta Yoshinaga
Date
2017.10.20
Definition at line 407 of file MyReversi.cs.
Referenced by Reversi4colorWpf.MyReversi.AnalysisReversi(), Reversi4colorWpf.MyReversi.AnalysisReversiBlack(), Reversi4colorWpf.MyReversi.AnalysisReversiBlue(), Reversi4colorWpf.MyReversi.AnalysisReversiRed(), Reversi4colorWpf.MyReversi.AnalysisReversiWhite(), Reversi4colorWpf.MyReversi.reset(), and Reversi4colorWpf.MyReversi.setMasuSts().
void Reversi4colorWpf.MyReversi.reset ()
リセット
Returns
ありません
Author
Yuta Yoshinaga
Date
2017.10.20
Definition at line 355 of file MyReversi.cs.
Referenced by Reversi4colorWpf.MyReversi.MyReversi(), Reversi4colorWpf.ReversiPlay.reset(), and Reversi4colorWpf.MyReversi.setMasuCnt().
void Reversi4colorWpf.MyReversi.revMasuSts (int color, int y, int x) [private]
コマをひっくり返す
Parameters
in int color ひっくり返す元コマ
in int y ひっくり返す元コマのY座標
in int x ひっくり返す元コマのX座標
Returns
ありません
Author
Yuta Yoshinaga
Date
2017.10.20
Definition at line 657 of file MyReversi.cs.
Referenced by Reversi4colorWpf.MyReversi.AnalysisReversiBlack(), Reversi4colorWpf.MyReversi.AnalysisReversiBlue(), Reversi4colorWpf.MyReversi.AnalysisReversiRed(), Reversi4colorWpf.MyReversi.AnalysisReversiWhite(), and Reversi4colorWpf.MyReversi.setMasuSts().
int Reversi4colorWpf.MyReversi.setMasuCnt (int cnt)
マスの数変更
Parameters
in int cnt マスの数
Returns
0 : 成功 それ以外 : 失敗
Author
Yuta Yoshinaga
Date
2017.10.20
Definition at line 1856 of file MyReversi.cs.
Referenced by Reversi4colorWpf.ReversiPlay.reset().
int Reversi4colorWpf.MyReversi.setMasuSts (int color, int y, int x)
指定座標にコマを置く
Parameters
in int color コマ色
in int y マスのY座標
in int x マスのX座標
Returns
0 : 成功 それ以外 : 失敗
Author
Yuta Yoshinaga
Date
2017.10.20
Definition at line 1804 of file MyReversi.cs.
Referenced by Reversi4colorWpf.ReversiPlay.reset(), Reversi4colorWpf.ReversiPlay.reversiPlay(), and Reversi4colorWpf.ReversiPlay.reversiPlayCpu().
int Reversi4colorWpf.MyReversi.setMasuStsForcibly (int color, int y, int x)
指定座標にコマを強制的に置く
Parameters
in int color コマ色
in int y マスのY座標
in int x マスのX座標
Returns
0 : 成功 それ以外 : 失敗
Author
Yuta Yoshinaga
Date
2017.10.20
Definition at line 1838 of file MyReversi.cs.
Referenced by Reversi4colorWpf.ReversiPlay.gameEndAnimExec().
The documentation for this class was generated from the following file:
Model/MyReversi.cs